//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.27 at 11:09:53 AM CST 
//


package org.cz.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="data" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fields">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="field" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                     &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="params" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="param" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="update-excludes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="update-exclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="increName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="fileSuffix">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="csv"/>
 *             &lt;enumeration value="xml"/>
 *             &lt;enumeration value="csv,xml"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="syncMode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="in"/>
 *             &lt;enumeration value="out"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="encoding" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="updateRecoder" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relativePath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="randomSuffix" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="cleanHistory" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data"
})
@XmlRootElement(name = "dataConvert")
public class DataConvert2 {

    @XmlElement(required = true)
    protected List<DataConvert.Data> data;
    @XmlAttribute(name = "fileSuffix")
    protected String fileSuffix;
    @XmlAttribute(name = "syncMode")
    protected String syncMode;
    @XmlAttribute(name = "encoding")
    protected String encoding;
    @XmlAttribute(name = "updateRecoder")
    protected String updateRecoder;
    @XmlAttribute(name = "relativePath")
    protected String relativePath;
    @XmlAttribute(name = "randomSuffix")
    protected Boolean randomSuffix;
    @XmlAttribute(name = "cleanHistory")
    protected Integer cleanHistory;

    /**
     * Gets the value of the data property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataConvert.Data }
     *
     *
     */
    public List<DataConvert.Data> getData() {
        if (data == null) {
            data = new ArrayList<DataConvert.Data>();
        }
        return this.data;
    }

    /**
     * Gets the value of the fileSuffix property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFileSuffix() {
        return fileSuffix;
    }

    /**
     * Sets the value of the fileSuffix property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFileSuffix(String value) {
        this.fileSuffix = value;
    }

    /**
     * Gets the value of the syncMode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSyncMode() {
        return syncMode;
    }

    /**
     * Sets the value of the syncMode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSyncMode(String value) {
        this.syncMode = value;
    }

    /**
     * Gets the value of the encoding property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the updateRecoder property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getUpdateRecoder() {
        return updateRecoder;
    }

    /**
     * Sets the value of the updateRecoder property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setUpdateRecoder(String value) {
        this.updateRecoder = value;
    }

    /**
     * Gets the value of the relativePath property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRelativePath() {
        return relativePath;
    }

    /**
     * Sets the value of the relativePath property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRelativePath(String value) {
        this.relativePath = value;
    }

    /**
     * Gets the value of the randomSuffix property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isRandomSuffix() {
        return randomSuffix;
    }

    /**
     * Sets the value of the randomSuffix property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setRandomSuffix(Boolean value) {
        this.randomSuffix = value;
    }

    /**
     * Gets the value of the cleanHistory property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getCleanHistory() {
        return cleanHistory;
    }

    /**
     * Sets the value of the cleanHistory property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setCleanHistory(Integer value) {
        this.cleanHistory = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fields">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="field" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                           &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="params" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="param" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="update-excludes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="update-exclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="increName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fields",
        "params",
        "updateExcludes"
    })
    public static class Data {

        @XmlElement(required = true)
        protected DataConvert.Data.Fields fields;
        protected DataConvert.Data.Params params;
        @XmlElement(name = "update-excludes")
        protected DataConvert.Data.UpdateExcludes updateExcludes;
        @XmlAttribute(name = "class")
        protected String clazz;
        @XmlAttribute(name = "increName")
        protected String increName;
        @XmlAttribute(name = "fullName")
        protected String fullName;

        /**
         * Gets the value of the fields property.
         *
         * @return
         *     possible object is
         *     {@link DataConvert.Data.Fields }
         *
         */
        public DataConvert.Data.Fields getFields() {
            return fields;
        }

        /**
         * Sets the value of the fields property.
         *
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.Fields }
         *
         */
        public void setFields(DataConvert.Data.Fields value) {
            this.fields = value;
        }

        /**
         * Gets the value of the params property.
         *
         * @return
         *     possible object is
         *     {@link DataConvert.Data.Params }
         *
         */
        public DataConvert.Data.Params getParams() {
            return params;
        }

        /**
         * Sets the value of the params property.
         *
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.Params }
         *
         */
        public void setParams(DataConvert.Data.Params value) {
            this.params = value;
        }

        /**
         * Gets the value of the updateExcludes property.
         *
         * @return
         *     possible object is
         *     {@link DataConvert.Data.UpdateExcludes }
         *
         */
        public DataConvert.Data.UpdateExcludes getUpdateExcludes() {
            return updateExcludes;
        }

        /**
         * Sets the value of the updateExcludes property.
         *
         * @param value
         *     allowed object is
         *     {@link DataConvert.Data.UpdateExcludes }
         *
         */
        public void setUpdateExcludes(DataConvert.Data.UpdateExcludes value) {
            this.updateExcludes = value;
        }

        /**
         * Gets the value of the clazz property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the increName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getIncreName() {
            return increName;
        }

        /**
         * Sets the value of the increName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setIncreName(String value) {
            this.increName = value;
        }

        /**
         * Gets the value of the fullName property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFullName(String value) {
            this.fullName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="field" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *                 &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "field"
        })
        public static class Fields {

            protected List<DataConvert.Data.Fields.Field> field;

            /**
             * Gets the value of the field property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the field property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getField().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.Fields.Field }
             *
             *
             */
            public List<DataConvert.Data.Fields.Field> getField() {
                if (field == null) {
                    field = new ArrayList<DataConvert.Data.Fields.Field>();
                }
                return this.field;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="unique" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *       &lt;attribute name="default" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Field {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;
                @XmlAttribute(name = "unique")
                protected Boolean unique;
                @XmlAttribute(name = "default")
                protected String _default;

                /**
                 * Gets the value of the content property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

                /**
                 * Gets the value of the unique property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *
                 */
                public Boolean isUnique() {
                    return unique;
                }

                /**
                 * Sets the value of the unique property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *
                 */
                public void setUnique(Boolean value) {
                    this.unique = value;
                }

                /**
                 * Gets the value of the default property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getDefault() {
                    return _default;
                }

                /**
                 * Sets the value of the default property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDefault(String value) {
                    this._default = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="param" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "param"
        })
        public static class Params {

            @XmlElement(required = true)
            protected List<DataConvert.Data.Params.Param> param;

            /**
             * Gets the value of the param property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the param property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParam().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DataConvert.Data.Params.Param }
             *
             *
             */
            public List<DataConvert.Data.Params.Param> getParam() {
                if (param == null) {
                    param = new ArrayList<DataConvert.Data.Params.Param>();
                }
                return this.param;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="target" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Param {

                @XmlValue
                protected String content;
                @XmlAttribute(name = "target")
                protected String target;

                /**
                 * Gets the value of the content property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContent() {
                    return content;
                }

                /**
                 * Sets the value of the content property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContent(String value) {
                    this.content = value;
                }

                /**
                 * Gets the value of the target property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTarget() {
                    return target;
                }

                /**
                 * Sets the value of the target property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTarget(String value) {
                    this.target = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="update-exclude" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "updateExclude"
        })
        public static class UpdateExcludes {

            @XmlElement(name = "update-exclude", required = true)
            protected List<String> updateExclude;

            /**
             * Gets the value of the updateExclude property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the updateExclude property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getUpdateExclude().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getUpdateExclude() {
                if (updateExclude == null) {
                    updateExclude = new ArrayList<String>();
                }
                return this.updateExclude;
            }

        }

    }

}
